# Generated by Django 4.2 on 2026-01-19 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('accident', 'Vehicle Accident'), ('fight', 'Fight/Altercation')], max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('frame_number', models.IntegerField()),
                ('timestamp', models.CharField(max_length=10)),
                ('video_path', models.CharField(max_length=500)),
                ('snapshot_path', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved')], default='new', max_length=20)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('vehicle_id', models.IntegerField()),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='SurveillanceApp.incident')),
            ],
            options={
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='CameraDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('frame_number', models.IntegerField()),
                ('timestamp', models.CharField(max_length=10)),
                ('matched_text', models.CharField(max_length=50)),
                ('snapshot_path', models.CharField(max_length=500)),
                ('confidence', models.FloatField(default=0.0)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='SurveillanceApp.vehicletracking')),
            ],
            options={
                'ordering': ['frame_number'],
            },
        ),
    ]
