# Generated by Django 4.2 on 2026-01-19 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SurveillanceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('camera_type', models.CharField(blank=True, choices=[('incident', 'Incident Detection'), ('tracking', 'Vehicle Tracking')], max_length=20, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='camera_feeds/')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManualSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('found', models.BooleanField(default=False)),
                ('searched_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('detection_confidence', models.FloatField()),
                ('total_ocr_scans', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('timestamp', models.CharField(max_length=20)),
                ('matched_text', models.CharField(max_length=20)),
                ('snapshot', models.ImageField(upload_to='vehicle_tracking/')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SurveillanceApp.camera')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='SurveillanceApp.vehicle')),
            ],
            options={
                'ordering': ['frame_number'],
            },
        ),
        migrations.RemoveField(
            model_name='vehicletracking',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='snapshot_path',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='video_path',
        ),
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='incident_snapshots/'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='detected_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('accident', 'Vehicle Accident'), ('fight', 'Fight Detected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='timestamp',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='CameraDetection',
        ),
        migrations.DeleteModel(
            name='VehicleTracking',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='SurveillanceApp.incident'),
        ),
        migrations.AddField(
            model_name='incident',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SurveillanceApp.camera'),
        ),
    ]
