# Generated by Django 4.2 on 2026-01-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SurveillanceApp', '0002_camera_manualsearch_vehicle_vehicledetection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='manualsearch',
            name='searched_by',
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehicledetection',
            options={'ordering': ['detected_at']},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='description',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='frame_number',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='total_ocr_scans',
        ),
        migrations.RemoveField(
            model_name='vehicledetection',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='vehicledetection',
            name='frame_number',
        ),
        migrations.AddField(
            model_name='vehicledetection',
            name='camera_location',
            field=models.CharField(default='Main Street Intersection', max_length=255),
        ),
        migrations.AddField(
            model_name='vehicledetection',
            name='camera_name',
            field=models.CharField(default='cam1', max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(default='Main Feed', max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='incidents/'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='detection_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='SurveillanceApp.incident'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicledetection',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='detections/'),
        ),
        migrations.AlterField(
            model_name='vehicledetection',
            name='timestamp',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='ManualSearch',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='search_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='SurveillanceApp.searchlog'),
        ),
    ]
