# Generated by Django 5.2.10 on 2026-03-12 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveillanceApp', '0004_incidentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentlog',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SurveillanceApp.incident'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('processing', 'Processing'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
