# SurveillanceProject\settings.py
"""
Django settings for SurveillanceProject project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

KAGGLE_API_URL = "https://bausond-martially-cherly.ngrok-free.dev"
DJANGO_CALLBACK_URL = " https://balladic-crysta-vocatively.ngrok-free.dev"

# Video catalog — add new videos here, they'll appear in the dashboard dropdown
KAGGLE_VIDEO_BASE_PATH = "/kaggle/input/datasets/akhilsiji21/roadsurveillance-testdata"
AVAILABLE_VIDEOS = [
    {"name": "Accident Video", "file": "accident.mp4", "type": "accident"},
    {"name": "Fight Video", "file": "fight1.mp4", "type": "fight"},
    {"name": "Normal Traffic", "file": "normal_traffic.mp4", "type": "accident"},
    {"name": "Normal Street", "file": "normal-street.mp4", "type": "fight"},
    #{"name": "Camera 1 Feed", "file": "cam1.mp4", "type": "accident"},
    #{"name": "Camera 2 Feed", "file": "cam2.mp4", "type": "accident"},
    #{"name": "Camera 3 Feed", "file": "cam3.mp4", "type": "accident"},
    #{"name": "Track 1", "file": "track1.mp4", "type": "accident"},
    #{"name": "Track 2", "file": "track2.mp4", "type": "accident"},
    #{"name": "Track 3", "file": "track3.mp4", "type": "accident"},
    #{"name": "Track 4", "file": "track4.mp4", "type": "accident"},
    {"name": "Fight Video 2", "file": "fight2.mp4", "type": "fight"},
    {"name": "Fight Video 3", "file": "fight3.mp4", "type": "fight"},
    #{"name": "Mahindra (Plate Track)", "file": "mahindra.mp4", "type": "accident"},
    #{"name": "Virtus (Plate Track)", "file": "virtus.mp4", "type": "accident"},
    {"name": "Accident Animation 1", "file": "accidentanimation01.mp4", "type": "accident"},
    {"name": "Accident Animation 2", "file": "accidentanimation02.mp4", "type": "accident"},
]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7@tb_x3!g(5!7&d9%&1a-9r^t1vms@!np-0+h5733ays4jifhc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.ngrok-free.app',
    '.ngrok-free.dev',
    '.ngrok.io',
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'SurveillanceApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SurveillanceProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SurveillanceProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Celery Configuration for background processing
CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'